name 'install_scripts'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Creates user, Installs/Configures install_scripts'
long_description 'Creates user, Installs/Configures install_scripts'
version '0.1.21'

depends 'apt', '~> 4.0.1'
depends 'test-helper'