name 'install_scripts'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures install_scripts'
long_description 'Installs/Configures install_scripts'
version '0.1.0'
