source "https://supermarket.chef.io"

metadata

group :integration do
  cookbook 'test-helper', path: '../test-helper'
end

cookbook 'chef-vault', '~> 1.3.2'
cookbook 'apt', '~> 3.0.0'
cookbook 'firewall', '~> 2.4.0'