source "https://supermarket.chef.io"

metadata

group :integration do
  cookbook 'test-helper', path: '../test-helper'
end

cookbook 'chef-vault', '~> 1.3.3'
cookbook 'apt', '~> 4.0.1'
cookbook 'firewall', '~> 2.5.2'