name 'basic_node'
maintainer 'Stefan Dieterle'
maintainer_email 'golgoths@yahoo.fr'
license 'GNU General Public License'
description 'Installs/Configures basic_node'
long_description 'Installs/Configures basic_node'
version '0.2.2'

depends 'apt', '~> 4.0.1'
depends 'test-helper'
depends 'chef-vault', '~> 1.3.3'
depends 'firewall', '~> 2.5.2'