name 'basic_node'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures basic_node'
long_description 'Installs/Configures basic_node'
version '0.1.5'

depends 'test-helper'
depends 'chef-vault', '~> 1.3.2'