---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.9.38
  log_file: "/var/log/chef-kitchen/chef-client.log"

platforms:
  - name: ubuntu-14.04
    driver:
      provider: libvirt
      box: prod-like
      provision: true
      vagrantfiles:
        - vagrant.rb
      customize:
        memory: 2048
        cpus: 2
  - name: centos-7.1
    driver:
      provider: libvirt
      box: centos/7

suites:
  - name: default
    driver:
      network:
        - ['private_network', {ip: '10.10.0.13'}]
        - ['public_network', {dev: 'br0', mode: 'bridge', type: 'bridge', ip: '192.168.1.83'}]
    run_list:
      - recipe[standalone_app_server::default]
      - recipe[test-helper::default]
    attributes:
      web_server:
        nginx:
          server_name: '192.168.1.83'
      django_app_server:
        django_app:
          allowed_host: '192.168.1.83'
    excludes: centos-7.1
  - name: reinstall_app
    driver:
      network:
        - ['private_network', {ip: '10.10.0.14'}]
        - ['public_network', {dev: 'br0', mode: 'bridge', type: 'bridge', ip: '192.168.1.84'}]
    run_list:
      - recipe[standalone_app_server::default]
      - recipe[standalone_app_server::reinstall_app]
      - recipe[test-helper::default]
    attributes:
      web_server:
        nginx:
          server_name: '192.168.1.84'
      django_app_server:
        django_app:
          allowed_host: '192.168.1.84'
    excludes: centos-7.1
