---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.9.38
  log_file: "/var/log/chef-kitchen/chef-client.log"

platforms:
  - name: ubuntu-14.04
    driver:
      provider: libvirt
      box: prod-like
      network:
        - ['private_network', {ip: '192.168.121.10'}]
        - ['public_network', {dev: 'br0', mode: 'bridge', type: 'bridge', ip: '192.168.1.82'}]
      customize:
        memory: 2048
        cpus: 2
  - name: centos-7.1
    driver:
      provider: libvirt
      box: centos/7

suites:
  - name: default
    run_list:
      - recipe[standalone_app_server::default]
      - recipe[test-helper::default]
    attributes:
    excludes: centos-7.1
