---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      provider: libvirt
      box: trusty64
      network:
        - ['private_network', {ip: '192.168.121.10'}]
      customize:
        memory: 2048
        cpus: 2
  - name: centos-7.1
    driver:
      provider: libvirt
      box: centos/7

suites:
  - name: default
    run_list:
      - recipe[web_server::default]
    attributes:
    excludes: centos-7.1
