---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.9.38
  log_file: "/var/log/chef-kitchen/chef-client.log"

platforms:
  - name: ubuntu-14.04
    driver:
      provider: libvirt
      box: alxgrh/ubuntu-trusty-x86_64
      network:
        - ['private_network', {ip: '10.10.0.12'}]
      customize:
        memory: 2048
        cpus: 2
  - name: ubuntu-16.04
    driver:
     provider: libvirt
     box: nrclark/xenial64-minimal-libvirt
     network:
       - ['private_network', {ip: '10.10.0.13'}]
     customize:
       memory: 2048
       cpus: 2
  - name: centos-7.1
    driver:
      provider: libvirt
      box: centos/7

suites:
  - name: default
    run_list:
      - recipe[db_server::default]
      - recipe[test-helper::default]
    attributes:
      db_server:
        postgresql:
          db_name: 'django_base'
    excludes:
      - centos-7.1
