source "https://supermarket.chef.io"

metadata

group :integration do
  cookbook 'test-helper', path: '../test-helper'
end

cookbook 'chef-vault', '~> 1.3.3'
cookbook 'apt', '~> 4.0.1'
cookbook 'postgresql', '~> 4.0.6'
cookbook 'database', '~> 5.1.2'
cookbook 'install_scripts', '~> 0.1.0', path: '../install_scripts'
