source "https://supermarket.chef.io"

metadata

group :integration do
  cookbook 'test-helper', path: '../test-helper'
end

cookbook 'chef-vault', '~> 1.3.2'
cookbook 'apt', '~> 3.0.0'
cookbook 'postgresql', '~> 4.0.0'
cookbook 'database', '~> 4.0.9'
cookbook 'install_scripts', '~> 0.1.0', path: '../install_scripts'
