---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  log_file: "/var/log/chef-kitchen/chef-client.log"

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec
#   format: doc

platforms:
  - name: ubuntu-16.04
    driver:
      provider: libvirt
      box: nrclark/xenial64-minimal-libvirt
      network:
        - ['private_network', {ip: '10.10.1.20'}]
        - ['public_network', {dev: 'br1', mode: 'bridge', type: 'bridge', ip: '192.168.1.87'}]
      customize:
        memory: 2048
        cpus: 2

suites:
  - name: default
    run_list:
      - recipe[chef_server::default]
      - recipe[test-helper::default]
    attributes:
