---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.9.38
  log_file: "/var/log/chef-kitchen/chef-client.log"

platforms:
  - name: ubuntu-14.04
    driver:
      provider: libvirt
      box: alxgrh/ubuntu-trusty-x86_64
      network:
        - ['private_network', {ip: '10.10.0.14'}]
      customize:
        memory: 2048
        cpus: 2
  - name: ubuntu-16.04
    driver:
     provider: libvirt
     box: nrclark/xenial64-minimal-libvirt
     network:
       - ['private_network', {ip: '10.10.0.15'}]
     customize:
       memory: 2048
       cpus: 2
  - name: centos-7.1
    driver:
      provider: libvirt
      box: centos/7

suites:
  - name: default
    run_list:
      - recipe[basic_node::firewall]
      - recipe[web_server::default]
      - recipe[test-helper::default]
    attributes:
    excludes: centos-7.1
