source "https://supermarket.chef.io"

metadata

group :integration do
  cookbook 'test-helper', path: '../test-helper'
end

cookbook 'chef-vault', '~> 1.3.3'
cookbook 'firewall', '~> 2.5.2'
cookbook 'apt', '~> 4.0.1'
cookbook 'basic_node', '~> 0.2.2', path: '../basic_node'
cookbook 'install_scripts', '~> 0.1.17', path: '../install_scripts'
cookbook 'django_app_server', '~> 0.2.8', path: '../django_app_server'
