---
driver:
  name: vagrant

provisioner:
  name: chef_solo
#  require_chef_omnibus: 12.11.18
  log_file: "/var/log/chef-kitchen/chef-client.log"

platforms:
  - name: ubuntu-14.04
    driver:
      provider: libvirt
      box: alxgrh/ubuntu-trusty-x86_64
# Use for public network
      provision: true
      vagrantfiles:
        - vagrant.rb
      network:
        - ['private_network', {ip: '10.10.1.14'}]
#        - ['private_network', {ip: '192.168.122.11'}]
        - ['public_network', {dev: 'br1', mode: 'bridge', type: 'bridge', ip: '192.168.1.82'}]
      customize:
        memory: 2048
        cpus: 2
    attributes:
      django_app_server:
        node_number: '000'
  - name: ubuntu-16.04
    driver:
     provider: libvirt
     box: nrclark/xenial64-minimal-libvirt
     network:
       - ['private_network', {ip: '10.10.1.15'}]
#       - ['private_network', {ip: '192.168.122.12'}]
       - ['public_network', {dev: 'br1', mode: 'bridge', type: 'bridge', ip: '192.168.1.83'}]
     customize:
       memory: 2048
       cpus: 2
    attributes:
      django_app_server:
        node_number: '001'
  - name: centos-7.1
    driver:
      provider: libvirt
      box: centos/7

suites:
  - name: default
    run_list:
      - recipe[django_app_server::default]
      - recipe[test-helper::default]
    excludes: centos-7.1
  - name: app
    run_list:
      - recipe[django_app_server::default]
      - recipe[test-helper::default]
    attributes:
      django_app_server:
        git:
          app_repo: 'https://github.com/globz-eu/django_base.git'
    excludes: centos-7.1
  - name: formalign
    run_list:
      - recipe[django_app_server::default]
      - recipe[test-helper::default]
    attributes:
      django_app_server:
        git:
          app_repo: 'https://github.com/globz-eu/formalign.git'
    excludes: centos-7.1
