source "https://supermarket.chef.io"

metadata

group :integration do
  cookbook 'test-helper', path: '../test-helper'
end

cookbook 'apt', '~> 4.0.1'
cookbook 'chef-vault', '~> 1.3.3'
cookbook 'poise-python', '~> 1.4.0'
cookbook 'install_scripts', '~> 0.1.1', path: '../install_scripts'
