source "https://supermarket.chef.io"

metadata

group :integration do
  cookbook 'test-helper', path: '../test-helper'
end

cookbook 'apt', '~> 3.0.0'
cookbook 'chef-vault', '~> 1.3.2'
cookbook 'poise-python', '~> 1.2.1'
cookbook 'install_scripts', '~> 0.1.0', path: '../install_scripts'
